#!/usr/bin/perl
$|++;
use strict;
use POSIX;
my $fg = shift || "yellow";
my $cmd = "xterm -fg $fg -bg black -sb -fn 10x20";

daemonize($cmd);

sub daemonize {
  my $cmd = shift;
  POSIX::setsid() or die "Can't start a new session: $!";
  fork and exit;
  POSIX::setsid();
  fork and exit;
  umask 0;
  chdir '/';
  print "Executing $cmd\n";
  exec($cmd);
  #close STDIN; #close STDOUT; #close STDERR;
}

